services:
  frontend:
    build: ./frontend
    ports: 
      - "8000:443"
    restart: always
  backend:
    build: ./backend
    ports:
      - "8002:5000"
    restart: always
    volumes:
      - /mnt/filestore/output/:/outputs
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    restart: always
    volumes:
      - /home/zhaoj16_ncbi_nlm_nih_gov/EzSEA/:/logs
