services:
  frontend:
    build: ./frontend
    ports: 
      - "8000:443"
  backend:
    build: ./backend
    ports:
      - "8002:5000"
    privileged: true
    volumes:
      - /mnt/filestore/output/:/outputs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  proxy:
    build: ./proxy
    ports:
      - "80:80"
